// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  about_us: dynamic(() => import('./AboutUs')),
  frequently_asked: dynamic(() => import('./FrequentlyAsked')),
  hero: dynamic(() => import('./Hero')),
  people: dynamic(() => import('./People')),
  resources: dynamic(() => import('./Resources')),
};
